// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgErgiKguc3v1qOOCdoGpTYvCDaH2WjY',
    appId: '1:95854848583:web:fd08bf4cd80be342a05f62',
    messagingSenderId: '95854848583',
    projectId: 'smarttravelerplanner',
    authDomain: 'smarttravelerplanner.firebaseapp.com',
    storageBucket: 'smarttravelerplanner.firebasestorage.app',
    measurementId: 'G-4DMNDL7NZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAXE6NhoaoJgUMn4MvmW8m9z5RCOHSkE',
    appId: '1:95854848583:android:933bc46517eca90ea05f62',
    messagingSenderId: '95854848583',
    projectId: 'smarttravelerplanner',
    storageBucket: 'smarttravelerplanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfBs6UGXwvFPkRMpmYNLWtG1aNOo3IUs',
    appId: '1:95854848583:ios:f46343fff8f6ce5fa05f62',
    messagingSenderId: '95854848583',
    projectId: 'smarttravelerplanner',
    storageBucket: 'smarttravelerplanner.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfBs6UGXwvFPkRMpmYNLWtG1aNOo3IUs',
    appId: '1:95854848583:ios:f46343fff8f6ce5fa05f62',
    messagingSenderId: '95854848583',
    projectId: 'smarttravelerplanner',
    storageBucket: 'smarttravelerplanner.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUgErgiKguc3v1qOOCdoGpTYvCDaH2WjY',
    appId: '1:95854848583:web:aa694dbb69318e81a05f62',
    messagingSenderId: '95854848583',
    projectId: 'smarttravelerplanner',
    authDomain: 'smarttravelerplanner.firebaseapp.com',
    storageBucket: 'smarttravelerplanner.firebasestorage.app',
    measurementId: 'G-X4R0CE3WYZ',
  );

}